-- Preconstructed decks, generated by scripts/build-precons.py.
-- Do not edit by hand.
--
-- PLACEHOLDERS: mono-colour decks so a player can start a match without
-- building one first. Not the real Black Swordsman / Hawks Soldiers starter
-- decks — see the script's docstring.

BEGIN;

-- Mono White (placeholder): 45 cards, 10 mercenaries
WITH deck AS (
    INSERT INTO decks (owner, name, precon) VALUES ('system', 'Mono White (placeholder)', true)
    RETURNING id
)
INSERT INTO deck_cards (deck_id, card_id, quantity)
SELECT deck.id, card_id, quantity
FROM deck, (VALUES
           ('BK1-001', 10),
           ('BK1-002', 3),
           ('BK1-003', 3),
           ('BK1-004', 3),
           ('BK1-005', 3),
           ('BK1-006', 3),
           ('BK1-007', 3),
           ('BK1-008', 3),
           ('BK1-009', 3),
           ('BK1-010', 3),
           ('BK1-011', 3),
           ('BK1-012', 3),
           ('BK1-013', 2)
     ) AS chosen (card_id, quantity);
-- Mono Green (placeholder): 45 cards, 10 mercenaries
WITH deck AS (
    INSERT INTO decks (owner, name, precon) VALUES ('system', 'Mono Green (placeholder)', true)
    RETURNING id
)
INSERT INTO deck_cards (deck_id, card_id, quantity)
SELECT deck.id, card_id, quantity
FROM deck, (VALUES
           ('BK1-041', 10),
           ('BK1-042', 3),
           ('BK1-043', 3),
           ('BK1-044', 3),
           ('BK1-045', 3),
           ('BK1-046', 3),
           ('BK1-047', 3),
           ('BK1-048', 3),
           ('BK1-049', 3),
           ('BK1-050', 3),
           ('BK1-051', 3),
           ('BK1-052', 3),
           ('BK1-053', 2)
     ) AS chosen (card_id, quantity);

COMMIT;
