import catalogue from './catalogue.json' with { type: 'json' };
import type { CardColor } from '../cards.js';

/**
 * The card database: every card that physically exists, keyed by its printed
 * number.
 *
 * Generated by `scripts/build-catalogue.py` from the extracted card images.
 * Fields that are printed on the card but not yet captured are `null` rather
 * than guessed — a plausible-looking wrong value is worse than a missing one,
 * because deck legality and play both key off these. `Docs/CardData.md`
 * records what is captured and what still has to be.
 */

/** Rules.md §3: Character cards, and Effect cards that are Normal or Eternal. */
/**
 * What the type line says a card is. The kinds were guessed at before the
 * card list existed; what is actually printed is `Character` or `Effect`,
 * with the Effect's kind (Normal / Eternal) beside it and `Quick` as a
 * separate marker — so those are `duration` and `quick`, not kinds.
 */
export type CardKindName = 'character' | 'effect';

export interface CatalogueCard {
  /** Printed card number, e.g. `BK1-007`. The stable key for a card. */
  readonly id: string;
  /** Set code, `BK1`-`BK5`. */
  readonly set: string;
  /** Number within the set. */
  readonly number: number;
  /** Path to the card art, relative to the card image root. */
  readonly image: string;

  /** Measured from the printed frame — known for every card. */
  readonly color: CardColor | null;
  /**
   * The card named "Mercenary": four per set, one per colour. Per
   * Docs/Deckbuilding.md a deck needs at least ten of these and may hold any
   * number — the exemption is by *name*, not by the `Mercenaries` faction.
   */
  readonly mercenary: boolean;
  /**
   * Not a Mercenary, but counts as one for `Deckbuilding.md`'s two rules —
   * because the card says so (BK3-002, BK3-050). Kept apart from
   * `mercenary`, which is the printed identity: the first card of each
   * colour block, named "Mercenary".
   */
  readonly mercenaryForDeckbuilding?: boolean;

  readonly name: string | null;
  /** Cost in the database notation from DesignNotes 8, e.g. `1B`, `RGB`. */
  readonly cost: string | null;
  /** Level, gated by City Level when opening. Rules.md §7. */
  readonly level: number | null;
  readonly type: CardKindName | null;
  /**
   * For an Effect, which kind. Rules.md §3 — a Normal resolves and goes to the
   * Trash; an Eternal stays on the table. Null for characters.
   */
  readonly duration: 'normal' | 'eternal' | null;
  /**
   * A Quick effect may interject out of turn. Rules.md §13. Captured, but the
   * priority stack that would use it is not built (§14).
   */
  readonly quick: boolean;
  /** Whether this is a Character card, as opposed to an Effect. */
  readonly character: boolean | null;
  /** Only one card of this name may be on the field. Rules.md §8. */
  readonly unique: boolean | null;

  readonly power: number | null;
  readonly hp: number | null;
  readonly range: number | null;
  readonly movement: number | null;
  /** Rules text as printed. Display only — behaviour lives in `abilities.ts`. */
  readonly effect: string | null;
  /**
   * A character's factions and roles, split into separate tokens by
   * `build-catalogue.py`: `Hawks/Cavalry` becomes `['hawk', 'cavalry']`.
   * Empty for Effect cards, whose type line carries a duration instead.
   */
  readonly subtypes: readonly string[];
}

export const CATALOGUE: readonly CatalogueCard[] = catalogue as CatalogueCard[];

export const CATALOGUE_BY_ID: ReadonlyMap<string, CatalogueCard> = new Map(
  CATALOGUE.map((card) => [card.id, card]),
);

/** Cards belonging to one set, in number order. */
export function cardsInSet(set: string): CatalogueCard[] {
  return CATALOGUE.filter((card) => card.set === set).sort((a, b) => a.number - b.number);
}

/** The cards named "Mercenary" — the ones a deck needs ten of. */
export const MERCENARIES: readonly CatalogueCard[] = CATALOGUE.filter((card) => card.mercenary);

export const SET_CODES: readonly string[] = [...new Set(CATALOGUE.map((c) => c.set))].sort();

/** How much of the database is filled in, for reporting progress. */
export function catalogueCoverage(): Record<string, number> {
  const total = CATALOGUE.length;
  const filled = (pick: (card: CatalogueCard) => unknown): number =>
    CATALOGUE.filter((card) => pick(card) !== null).length;
  return {
    total,
    color: filled((c) => c.color),
    name: filled((c) => c.name),
    cost: filled((c) => c.cost),
    level: filled((c) => c.level),
    type: filled((c) => c.type),
    power: filled((c) => c.power),
    hp: filled((c) => c.hp),
    range: filled((c) => c.range),
    movement: filled((c) => c.movement),
    effect: filled((c) => c.effect),
  };
}
