#!/usr/bin/env python3
"""
Generate the card seed SQL that initialises the database.

Reads the card database (`packages/engine/src/data/catalogue.json`) and writes
`db/init/02-cards.sql`, which Postgres runs on first start — the official image
executes everything in /docker-entrypoint-initdb.d in name order, so the schema
in 01-schema.sql lands first and this fills it.

The insert is idempotent: re-running it updates existing rows rather than
failing, so regenerating the seed after capturing more card data and restarting
is enough to bring the database up to date.

Usage:
    python3 scripts/build-db-seed.py
"""

from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CATALOGUE = REPO / "packages" / "engine" / "src" / "data" / "catalogue.json"
OUT = REPO / "db" / "init" / "02-cards.sql"

COLUMNS = [
    "id",
    "set_code",
    "number",
    "image",
    "color",
    "mercenary",
    "name",
    "cost",
    "level",
    "type",
    "duration",
    "is_quick",
    "is_character",
    "is_unique",
    "power",
    "hp",
    "range",
    "movement",
    "effect",
]

# catalogue.json field -> column, where the names differ.
RENAMES = {
    "set": "set_code",
    "character": "is_character",
    "unique": "is_unique",
    "quick": "is_quick",
}


def literal(value: object) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def main() -> int:
    cards = json.loads(CATALOGUE.read_text(encoding="utf-8"))

    rows = []
    for card in cards:
        record = {RENAMES.get(k, k): v for k, v in card.items()}
        rows.append("    (" + ", ".join(literal(record.get(c)) for c in COLUMNS) + ")")

    updates = ",\n".join(
        f"    {column} = EXCLUDED.{column}" for column in COLUMNS if column != "id"
    )

    sql = f"""-- Card data for all {len(cards)} cards, generated by scripts/build-db-seed.py.
-- Do not edit by hand: regenerate after updating the card database with
--     python3 scripts/build-catalogue.py && python3 scripts/build-db-seed.py
--
-- Fields still to be captured from the card images are NULL rather than
-- guessed; see Docs/CardData.md.

BEGIN;

INSERT INTO cards ({", ".join(COLUMNS)}) VALUES
{",\n".join(rows)}
ON CONFLICT (id) DO UPDATE SET
{updates};

COMMIT;
"""

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(sql, encoding="utf-8")

    known = lambda field: sum(1 for c in cards if c.get(field) is not None)  # noqa: E731
    print(f"wrote {OUT.relative_to(REPO)}  ({len(cards)} cards, {OUT.stat().st_size // 1024} KB)")
    print("  populated:")
    for field in (
        "color",
        "mercenary",
        "name",
        "level",
        "type",
        "duration",
        "quick",
        "power",
        "hp",
        "range",
        "movement",
    ):
        print(f"    {field:<10} {known(field):>3}/{len(cards)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
