#!/usr/bin/env python3
"""
Build the preconstructed decks that ship with the game.

Writes `db/init/04-precons.sql`, which Postgres runs on first start after the
card seed. Precons belong to no player: `decks.precon` is true, and every
player sees them alongside their own decks.

These two are PLACEHOLDERS — mono-white and mono-green decks assembled from
the card database so a player can jump straight into a match without building
anything first. They are not the real Black Swordsman and Hawks Soldiers
starter decks: those lists are not published anywhere machine-readable, and
mapping one would need the printed card names, which are not captured yet
(see Docs/CardData.md). Replace this file's DECKS when the real lists arrive.

Each deck satisfies Docs/Deckbuilding.md: exactly 45 cards, at most 3 copies of
any card, at least 10 mercenaries — the mercenary being exempt from the cap.

Usage:
    python3 scripts/build-precons.py
"""

from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CATALOGUE = REPO / "packages" / "engine" / "src" / "data" / "catalogue.json"
OUT = REPO / "db" / "init" / "04-precons.sql"

DECK_SIZE = 45
MAX_COPIES = 3
MERCENARIES = 10

# Placeholder decks, by colour. Names say plainly what they are.
DECKS = [
    ("Mono White (placeholder)", "white"),
    ("Mono Green (placeholder)", "green"),
]

# A precon has no owner; this is the sentinel the decks table stores.
SYSTEM_OWNER = "system"


def build(cards: list[dict], colour: str) -> list[tuple[str, int]]:
    """A legal 45-card deck in one colour."""
    pool = [c for c in cards if c["color"] == colour]
    mercenary = next(c for c in pool if c["mercenary"])

    # Characters first: a deck of nothing but effects has no way to take a city.
    others = sorted(
        (c for c in pool if not c["mercenary"]),
        key=lambda c: (not c["character"], c["set"], c["number"]),
    )

    entries: list[tuple[str, int]] = [(mercenary["id"], MERCENARIES)]
    remaining = DECK_SIZE - MERCENARIES
    for card in others:
        if remaining == 0:
            break
        take = min(MAX_COPIES, remaining)
        entries.append((card["id"], take))
        remaining -= take

    if remaining:
        raise RuntimeError(f"not enough {colour} cards to fill a deck")
    return entries


def check(entries: list[tuple[str, int]], cards: dict[str, dict]) -> None:
    """The same rules the engine enforces, so a bad precon never ships."""
    size = sum(q for _, q in entries)
    if size != DECK_SIZE:
        raise RuntimeError(f"deck is {size} cards, must be {DECK_SIZE}")

    mercs = sum(q for cid, q in entries if cards[cid]["mercenary"])
    if mercs < MERCENARIES:
        raise RuntimeError(f"deck has {mercs} mercenaries, needs {MERCENARIES}")

    for cid, quantity in entries:
        if not cards[cid]["mercenary"] and quantity > MAX_COPIES:
            raise RuntimeError(f"{cid}: {quantity} copies exceeds {MAX_COPIES}")


def main() -> int:
    cards = json.loads(CATALOGUE.read_text(encoding="utf-8"))
    by_id = {c["id"]: c for c in cards}

    blocks = []
    for name, colour in DECKS:
        entries = build(cards, colour)
        check(entries, by_id)

        values = ",\n           ".join(
            f"('{cid}', {quantity})" for cid, quantity in entries
        )
        blocks.append(
            f"""-- {name}: {sum(q for _, q in entries)} cards, """
            f"""{sum(q for cid, q in entries if by_id[cid]['mercenary'])} mercenaries
WITH deck AS (
    INSERT INTO decks (owner, name, precon) VALUES ('{SYSTEM_OWNER}', '{name}', true)
    RETURNING id
)
INSERT INTO deck_cards (deck_id, card_id, quantity)
SELECT deck.id, card_id, quantity
FROM deck, (VALUES
           {values}
     ) AS chosen (card_id, quantity);"""
        )
        print(f"  {name}: {len(entries)} distinct, {sum(q for _, q in entries)} cards")

    sql = f"""-- Preconstructed decks, generated by scripts/build-precons.py.
-- Do not edit by hand.
--
-- PLACEHOLDERS: mono-colour decks so a player can start a match without
-- building one first. Not the real Black Swordsman / Hawks Soldiers starter
-- decks — see the script's docstring.

BEGIN;

{chr(10).join(blocks)}

COMMIT;
"""

    OUT.write_text(sql, encoding="utf-8")
    print(f"\nwrote {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
